<?php

namespace BackendBundle\Repository;

/**
 * Batiment_hdvRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Batiment_hdvRepository extends \Doctrine\ORM\EntityRepository
{
}
